const previewCardStyle=new URLSearchParams(location.search).get('cardStyle');const selectedCardStyle=['neon-terminal','holographic-glass','circuit-board','night-city','corporate-firewall'].includes(previewCardStyle)?previewCardStyle:'holographic-glass';document.documentElement.dataset.cardStyle=selectedCardStyle;const state={pool:[],deck:{},rules:[],session:null,match:null,matchData:null,logNumber:null,battlePage:0,logPage:0,running:false,selectedRule:undefined,deckReady:false,deckKey:null,view:'deck',config:{minimum_deck_size:20,maximum_deck_size:30}};
const $=id=>document.getElementById(id);const card=id=>state.pool.find(c=>c.card_id===id)||{display_name:id,effect:'',victory_points:0};const name=id=>card(id).display_name;
const esc=value=>String(value??'').replace(/[&<>\"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[char]));
function options(select,ids,selected){select.innerHTML=ids.map(id=>'<option value="'+esc(id)+'" '+(id===selected?'selected':'')+'>'+esc(name(id))+'</option>').join('')}
const deckStorageKey='cybernet-decks-v1';
function loadSavedDecks(){try{return JSON.parse(localStorage.getItem(deckStorageKey)||'[]')}catch(_error){return []}}
function saveSavedDecks(decks){localStorage.setItem(deckStorageKey,JSON.stringify(decks))}
function savedDeckKey(owner,name){return owner+'::'+name}
function renderSavedDecks(){const owner=$('owner').value.trim(),select=$('saved-decks'),chosen=select.value,decks=loadSavedDecks().filter(deck=>deck.owner_name===owner),creating=!$('new-deck-wrap').hidden;select.innerHTML='<option value="">Select a saved deck</option>'+decks.map(deck=>'<option value="'+esc(savedDeckKey(deck.owner_name,deck.name))+'">'+esc(deck.name)+'</option>').join('');if(decks.some(deck=>savedDeckKey(deck.owner_name,deck.name)===chosen))select.value=chosen;$('confirm-deck').disabled=!select.value&&(!creating||!$('deck-name').value.trim())}
function persistSelectedDeck(){if(!state.deckReady||!state.deckKey)return;const record=currentDeckPayload(),decks=loadSavedDecks().filter(deck=>savedDeckKey(deck.owner_name,deck.name)!==state.deckKey);decks.push(record);saveSavedDecks(decks)}
function activateDeck(){state.deckReady=true;$('deck-setup').hidden=true;$('workflow-nav').hidden=false;$('status').hidden=false;$('status').textContent='';renderDeck();renderRules();persistSelectedDeck();setView('deck')}
function deckIds(){return Object.keys(state.deck)}function deckSize(){return Object.values(state.deck).reduce((total,count)=>total+count,0)}
function deckMessage(){const total=deckSize(),min=state.config.minimum_deck_size,max=state.config.maximum_deck_size;if(total<min)return total+' / '+min+'–'+max+' cards — add '+(min-total)+' more to continue.';if(total>max)return total+' / '+min+'–'+max+' cards — remove '+(total-max)+' to continue.';return total+' / '+min+'–'+max+' cards — ready to continue.'}
function conditionText(type,threshold,cardId){if(type==='card_in_hand')return name(cardId)+' is in your hand';if(type==='own_victory_points_at_most')return 'your victory points are '+threshold+' or less';return 'opponent victory points are '+threshold+' or less'}
function actionText(type,cardId){if(type==='play_random_card')return 'play a random card';if(type==='end_turn')return 'end your turn';return 'play '+name(cardId)}
function ruleText(condition,threshold,conditionCard,action,actionCard){const actionLabel=actionText(action,actionCard);if(condition==='if_able')return actionLabel.charAt(0).toUpperCase()+actionLabel.slice(1)+' if able.';return 'If '+conditionText(condition,threshold,conditionCard)+', '+actionLabel+'.'}
function setView(view){if(!state.deckReady)return;if(view==='results'&&!state.session)return;if(view==='logs'&&(!state.session||!state.match||state.logNumber===null))return;state.view=view;const order=['deck','program','results','logs'],current=order.indexOf(view);document.querySelectorAll('.view').forEach(panel=>panel.hidden=panel.id!=='view-'+view);document.querySelectorAll('.workflow button').forEach(button=>{button.classList.toggle('active',button.dataset.view===view);button.classList.toggle('complete',order.indexOf(button.dataset.view)<current)});updateNavigation();window.scrollTo(0,0)}
function updateNavigation(){document.querySelector('[data-view="results"]').disabled=!state.session;document.querySelector('[data-view="logs"]').disabled=!state.session||!state.match||state.logNumber===null}
function updateDeckValidity(){const valid=deckSize()>=state.config.minimum_deck_size&&deckSize()<=state.config.maximum_deck_size;const message=deckMessage();$('deck-validity').textContent=message;$('deck-validity').classList.toggle('valid',valid);$('continue-to-program').disabled=!valid;$('submit').disabled=state.running||!valid;$('submit').textContent=state.running?'Simulating…':valid?'Simulate':'Need '+Math.max(0,state.config.minimum_deck_size-deckSize())+' more cards'}
function renderCardGallery(){const filter=($('card-filter').value||'').toLowerCase().trim();const cards=state.pool.filter(c=>(c.display_name+' '+c.effect).toLowerCase().includes(filter));$('card-result-count').textContent=filter?cards.length+' card'+(cards.length===1?'':'s')+' match “'+$('card-filter').value+'”':cards.length+' cards available';$('card-gallery').innerHTML=cards.map(c=>{const count=state.deck[c.card_id]||0;return '<div class="builder-card"><h4>'+esc(c.display_name)+'</h4><p>'+esc(c.effect)+'</p><span class="card-meta">'+count+' in deck'+(c.victory_points?' · '+c.victory_points+' VP':'')+'</span><button class="add-card" data-add-card="'+esc(c.card_id)+'">'+(count?'Add another':'Add card')+'</button></div>'}).join('')||'<small>No cards match this filter.</small>'}
function currentDeckPayload(){return {owner_name:$('owner').value,name:$('deck-name').value,decklist:state.deck,program:state.rules.map(rule=>{const copy={...rule};if(copy.energy_threshold!==undefined){copy.victory_points_threshold=copy.energy_threshold;delete copy.energy_threshold}return copy})}}
function deckReferenceHtml(d,showProgram=true){const cards=Object.entries(d.decklist||{}).map(([id,count])=>'<div class="preview-card"><div class="preview-meta"><strong>'+esc(count)+'× '+esc(name(id))+'</strong><small>'+esc(card(id).effect)+'</small></div><span>'+(card(id).victory_points||0)+' VP</span></div>').join('')||'<p class="empty-state">No cards selected.</p>';const rules=(d.program||[]).map((r,i)=>(i+1)+'. '+ruleText(r.condition_type,r.victory_points_threshold??r.energy_threshold,r.condition_card_id,r.action_type,r.action_card_id)).join(' ')||'Default random play.';return '<div class="compact-deck"><h3>'+esc(d.owner_name||'Player')+(d.name?' · '+esc(d.name):'')+'</h3><div class="deck-preview">'+cards+'</div>'+(showProgram?'<p class="compact-program"><strong>Program:</strong> '+esc(rules)+'</p>':'')+'</div>'}
function renderDeckPreview(){const d=currentDeckPayload();$('deck-preview').innerHTML=Object.entries(d.decklist).map(([id,count])=>'<div class="preview-card"><div class="preview-meta"><strong>'+esc(name(id))+'</strong><small>'+esc(card(id).effect)+'</small></div><div class="preview-controls"><button class="quantity-button" data-copy-adjust="'+esc(id)+'" data-delta="-1">−</button><span class="quantity-value">'+count+'</span><button class="quantity-button" data-copy-adjust="'+esc(id)+'" data-delta="1">+</button><button class="quantity-button" data-remove="'+esc(id)+'">×</button></div></div>').join('')||'<p class="empty-state">Add cards to see your decklist.</p>';$('deck-preview-summary').textContent=deckSize()+' / '+state.config.minimum_deck_size+'–'+state.config.maximum_deck_size+' cards';$('deck-preview-summary').classList.toggle('valid',deckSize()>=state.config.minimum_deck_size&&deckSize()<=state.config.maximum_deck_size);$('program-deck-preview').innerHTML=deckReferenceHtml(d,false);$('program-deck-summary').textContent=deckSize()+' cards · '+state.rules.length+' programmed rule'+(state.rules.length===1?'':'s')}
function renderConditionParameters(){const cardCondition=$('condition-type').value==='card_in_hand'&&deckIds().length>0;$('condition-card-wrap').hidden=!cardCondition;$('condition-energy-wrap').hidden=$('condition-type').value==='card_in_hand';renderRuleSentence()}
function renderRuleSelectors(){const ids=deckIds();options($('action-card'),ids,ids[0]);$('action-card-wrap').hidden=$('action-type').value!=='play_named_card'||!ids.length;renderRuleSentence()}
function renderRuleSentence(){const condition=$('condition-type').value;const threshold=$('condition-energy').value;const conditionCard=$('condition-card').value;const action=$('action-type').value;const actionCard=$('action-card').value;$('rule-sentence').textContent=ruleText(condition,threshold,conditionCard,action,actionCard)}
function renderRules(){const list=$('rules');list.innerHTML=state.rules.map((r,i)=>'<li data-rule="'+i+'" class="'+(i===state.selectedRule?'selected':'')+'"><span class="rule-priority">'+(i+1)+'</span><span class="rule-copy"><strong>'+esc(ruleText(r.condition_type,r.victory_points_threshold??r.energy_threshold,r.condition_card_id,r.action_type,r.action_card_id))+'</strong><small>'+(i===0?'Highest priority rule.':'Runs after the rules above.')+'</small></span></li>').join('')||'<li class="empty-state">No rules yet. The game will play a random card when it needs to act.</li>';renderDeckPreview()}
function renderDeck(){const ids=deckIds();renderCardGallery();options($('condition-card'),ids,ids[0]);renderConditionParameters();renderRuleSelectors();renderDeckPreview();updateDeckValidity();persistSelectedDeck()}
function moveRule(n){const i=state.selectedRule,j=i+n;if(i!==undefined&&j>=0&&j<state.rules.length){[state.rules[i],state.rules[j]]=[state.rules[j],state.rules[i]];state.selectedRule=j;renderRules()}}
document.addEventListener('click',event=>{const viewButton=event.target.closest('[data-view]');if(viewButton){setView(viewButton.dataset.view);return}const add=event.target.dataset.addCard;if(add){state.deck[add]=(state.deck[add]||0)+1;renderDeck();return}const adjust=event.target.closest('[data-copy-adjust]');if(adjust){const id=adjust.dataset.copyAdjust;const next=(state.deck[id]||0)+Number(adjust.dataset.delta);if(next>0)state.deck[id]=next;else delete state.deck[id];renderDeck();return}const remove=event.target.dataset.remove;if(remove){delete state.deck[remove];renderDeck();return}const rule=event.target.closest('[data-rule]');if(rule){state.selectedRule=+rule.dataset.rule;renderRules();return}const opponent=event.target.closest('[data-opponent]');if(opponent){match(opponent.dataset.opponent);return}const battle=event.target.closest('[data-battle]');if(battle)log(+battle.dataset.battle)});
document.addEventListener('input',event=>{if(event.target.id==='card-filter')renderCardGallery()});document.addEventListener('change',event=>{const cardId=event.target.dataset.copy;if(cardId){const count=Math.max(0,+event.target.value||0);if(count)state.deck[cardId]=count;else delete state.deck[cardId];renderDeck()}});
$('create-deck').onclick=()=>{const owner=$('owner').value.trim(),deckName=$('deck-name').value.trim();if(!owner||!deckName)return;$('owner').value=owner;$('deck-name').value=deckName;state.deckReady=true;$('deck-setup').hidden=true;$('workflow-nav').hidden=false;$('status').hidden=false;$('status').textContent='';setView('deck')};$('continue-to-program').onclick=()=>{if(deckSize()>=state.config.minimum_deck_size&&deckSize()<=state.config.maximum_deck_size){$('status').textContent='';setView('program')}};if($('back-to-deck'))$('back-to-deck').onclick=()=>setView('deck');$('back-to-matchups').onclick=()=>{state.match=null;state.matchData=null;state.logNumber=null;$('match-panel').hidden=true;$('results-table-wrap').hidden=false;$('status').textContent='Simulation complete.';updateNavigation();setView('results')};$('back-to-battles').onclick=()=>setView('results');$('condition-type').onchange=renderConditionParameters;$('condition-energy').onchange=renderRuleSentence;$('condition-card').onchange=renderRuleSentence;$('action-type').onchange=renderRuleSelectors;$('action-card').onchange=renderRuleSentence;$('add-rule').onclick=()=>{const ids=deckIds(),condition=$('condition-type').value,action=$('action-type').value;if(!ids.length)return;const rule={condition_type:condition,action_type:action};if(condition==='card_in_hand')rule.condition_card_id=$('condition-card').value;else rule.energy_threshold=+$('condition-energy').value;if(action==='play_named_card')rule.action_card_id=$('action-card').value;state.rules.push(rule);state.selectedRule=state.rules.length-1;renderRules()};$('remove-rule').onclick=()=>{if(state.selectedRule!==undefined){state.rules.splice(state.selectedRule,1);state.selectedRule=undefined;renderRules()}};$('rule-up').onclick=()=>moveRule(-1);$('rule-down').onclick=()=>moveRule(1);
function renderCardGallery(){const filter=($('card-filter').value||'').toLowerCase().trim();const cards=state.pool.filter(c=>(c.display_name+' '+c.effect+' '+c.card_kind_label).toLowerCase().includes(filter));$('card-result-count').textContent=filter?cards.length+' card'+(cards.length===1?'':'s')+' match the filter':cards.length+' cards available';$('card-gallery').innerHTML=cards.map(c=>{const count=state.deck[c.card_id]||0;return '<div class="card-selection"><article class="builder-card"><div class="card-titlebar"><h4>'+esc(c.display_name)+'</h4></div><div class="card-art-frame"><img src="'+esc(c.art_url)+'" alt="'+esc(c.art_alt)+'" style="object-position:'+esc(c.art_position)+'" loading="lazy"></div><div class="card-typebar"><span>'+esc(c.card_kind_label)+'</span></div><div class="card-rules"><p>'+esc(c.effect)+'</p></div></article><div class="card-choice"><span class="card-count">'+count+' in deck</span><button class="add-card" data-add-card="'+esc(c.card_id)+'">'+(count?'Add another':'Add card')+'</button></div></div>'}).join('')||'<small>No cards match this filter.</small>'}
Promise.all([fetch('data/format.json').then(response=>response.json()),fetch('data/opponents.json').then(response=>response.json())]).then(([data,opponents])=>{state.publicOpponents=opponents;state.pool=data.cards;state.config=data.config;options($('condition-energy'),Array.from({length:21},(_,index)=>String(index)),'5');renderDeck();renderRules();renderSavedDecks();updateNavigation()});
$('show-new-deck').onclick=()=>{$('saved-decks').value='';$('new-deck-wrap').hidden=false;$('deck-name').focus();renderSavedDecks()};$('saved-decks').onchange=()=>{if($('saved-decks').value){$('new-deck-wrap').hidden=true;renderSavedDecks()}};$('owner').oninput=renderSavedDecks;$('deck-name').oninput=renderSavedDecks;$('confirm-deck').onclick=()=>{const owner=$('owner').value.trim(),selected=$('saved-decks').value,deckName=$('deck-name').value.trim();if(!owner)return;if(selected){const saved=loadSavedDecks().find(deck=>savedDeckKey(deck.owner_name,deck.name)===selected);if(!saved)return;$('deck-name').value=saved.name;state.deck={...saved.decklist};state.rules=[...saved.program];state.deckKey=selected}else{if(deckName==='')return;state.deck={};state.rules=[];state.selectedRule=undefined;state.deckKey=savedDeckKey(owner,deckName)}activateDeck()};renderSavedDecks();$('save-deck').onclick=()=>{persistSelectedDeck();$('status').textContent='Deck saved.'};
function exportDeckCode(){const ids=state.pool.map(card=>card.card_id),index=new Map(ids.map((id,i)=>[id,i])),bytes=ids.map(id=>state.deck[id]||0);bytes.push(state.rules.length);for(const rule of state.rules){const condition={if_able:0,card_in_hand:1,own_victory_points_at_most:2,opponent_victory_points_at_most:3}[rule.condition_type],action={play_named_card:0,play_random_card:1,end_turn:2}[rule.action_type];if(condition===undefined||action===undefined)throw Error('This deck has an unsupported rule.');bytes.push((condition<<4)|action);if(condition===1)bytes.push(index.get(rule.condition_card_id));else if(condition===2||condition===3)bytes.push(rule.victory_points_threshold??rule.energy_threshold);if(action===0)bytes.push(index.get(rule.action_card_id));}return 'CD1'+btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function copyExportCode(code){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(code);return}const input=document.createElement('textarea');input.value=code;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();if(!document.execCommand('copy'))throw Error('Clipboard access was denied.');input.remove()}
$('export-deck').onclick=async()=>{try{if(deckSize()<state.config.minimum_deck_size||deckSize()>state.config.maximum_deck_size)throw Error(deckMessage());if(state.rules.length>255)throw Error('A deck can export at most 255 program rules.');persistSelectedDeck();const code=exportDeckCode();await copyExportCode(code);$('status').textContent='Discord export code copied to your clipboard ('+code.length+' characters). Run /netdeck in Discord and paste it into the import box.'}catch(error){$('status').textContent='Could not export this deck. '+error.message}};
function conditionText(type,threshold,cardId){if(type==='if_able')return 'if able';if(type==='card_in_hand')return name(cardId)+' is in your hand';if(type==='own_victory_points_at_most')return 'your victory points are '+threshold+' or less';return 'opponent victory points are '+threshold+' or less'}
function renderConditionParameters(){const type=$('condition-type').value,cardCondition=type==='card_in_hand'&&deckIds().length>0,thresholdCondition=type!=='card_in_hand'&&type!=='if_able';$('condition-card-wrap').hidden=!cardCondition;$('condition-energy-wrap').hidden=!thresholdCondition;renderRuleSentence()}
function moveRuleAt(from,to){if(from===to||from<0||to<0||from>=state.rules.length||to>=state.rules.length)return;const moved=state.rules.splice(from,1)[0];state.rules.splice(to,0,moved);state.selectedRule=to;renderRules()}
function removeRuleFromProgram(index){if(index<0||index>=state.rules.length)return;state.rules.splice(index,1);state.selectedRule=undefined;renderRules()}
function renderRules(){const list=$('rules');list.innerHTML=state.rules.map((r,i)=>'<li data-rule="'+i+'" draggable="true" class="'+(i===state.selectedRule?'selected':'')+'"><span class="rule-priority">'+(i+1)+'</span><span class="rule-copy"><strong>If '+esc(conditionText(r.condition_type,r.victory_points_threshold??r.energy_threshold,r.condition_card_id))+', '+esc(actionText(r.action_type,r.action_card_id))+'.</strong><small>'+(i===0?'Highest priority rule.':'Runs after the rules above.')+'</small></span><button class="delete-rule" type="button" aria-label="Delete rule '+(i+1)+'" onclick="removeRuleFromProgram('+i+')">×</button></li>').join('')||'<li class="empty-state">No rules yet. The game will play a random card when it needs to act.</li>';renderDeckPreview()}
$('add-rule').onclick=()=>{const ids=deckIds(),condition=$('condition-type').value,action=$('action-type').value;if(!ids.length)return;const rule={condition_type:condition,action_type:action};if(condition==='card_in_hand')rule.condition_card_id=$('condition-card').value;else if(condition!=='if_able')rule.energy_threshold=+$('condition-energy').value;if(action==='play_named_card')rule.action_card_id=$('action-card').value;state.rules.push(rule);state.selectedRule=state.rules.length-1;renderRules()};
let draggedRuleIndex;
document.addEventListener('dragstart',event=>{const row=event.target.closest('[data-rule]');if(!row)return;draggedRuleIndex=+row.dataset.rule;row.classList.add('dragging');if(event.dataTransfer)event.dataTransfer.effectAllowed='move'});
document.addEventListener('dragover',event=>{const row=event.target.closest('[data-rule]');if(!row||draggedRuleIndex===undefined)return;event.preventDefault();document.querySelectorAll('[data-rule]').forEach(candidate=>candidate.classList.remove('drag-over'));if(+row.dataset.rule!==draggedRuleIndex)row.classList.add('drag-over')});
document.addEventListener('drop',event=>{const row=event.target.closest('[data-rule]');if(!row||draggedRuleIndex===undefined)return;event.preventDefault();moveRuleAt(draggedRuleIndex,+row.dataset.rule);draggedRuleIndex=undefined});
document.addEventListener('dragend',event=>{const row=event.target.closest('[data-rule]');if(row)row.classList.remove('dragging');document.querySelectorAll('[data-rule]').forEach(candidate=>candidate.classList.remove('drag-over'));draggedRuleIndex=undefined});
let pointerRule;
document.addEventListener('pointerdown',event=>{const row=event.target.closest('[data-rule]');if(!row||event.target.closest('button'))return;pointerRule={index:+row.dataset.rule,row};row.classList.add('dragging')});
document.addEventListener('pointerup',event=>{if(!pointerRule)return;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-rule]');if(target&&+target.dataset.rule!==pointerRule.index)moveRuleAt(pointerRule.index,+target.dataset.rule);pointerRule.row.classList.remove('dragging');document.querySelectorAll('[data-rule]').forEach(candidate=>candidate.classList.remove('drag-over'));pointerRule=undefined});
document.addEventListener('pointercancel',()=>{if(pointerRule){pointerRule.row.classList.remove('dragging');pointerRule=undefined}});

/* TypeScript engine worker: compact records are retained; logs are replayed on demand. */
let simulationWorker;state.browserMatches=[];state.browserSubmission=null;
function browserWinRate(match){const total=match.wins+match.losses+match.draws;return total?match.wins/total*100:0}
function browserWinRateCell(match,previousRates){const rate=browserWinRate(match),previous=previousRates[match.opponent],delta=previous===undefined?0:rate-previous;if(previous===undefined||Math.abs(delta)<=0.1)return '<td>'+rate.toFixed(1)+'%</td>';const direction=delta>0?'up':'down',sign=delta>0?'+':'';return '<td>'+rate.toFixed(1)+'% <span class="win-rate-'+direction+' win-rate-change">('+sign+delta.toFixed(1)+'%)</span></td>'}
function worker(){if(simulationWorker)return simulationWorker;const script=document.querySelector('script[src$="/app.js"]');const workerUrl=new URL('engine/simulation-worker.js',script?script.src:location.href);simulationWorker=new Worker(workerUrl,{type:'module'});const failed=message=>{state.running=false;$('simulation-progress').hidden=true;$('status').textContent='Could not start the simulation worker: '+message;updateNavigation();simulationWorker=undefined};simulationWorker.onerror=event=>failed(event.message||'the worker script could not load.');simulationWorker.onmessageerror=()=>failed('the worker returned unreadable data.');simulationWorker.onmessage=event=>{const data=event.data;if(data.type==='progress'){$('simulation-progress').max=data.total;$('simulation-progress').value=data.completed;$('status').textContent='Simulating '+data.completed+' of '+data.total+' sample decks ('+Math.round(data.completed/data.total*100)+'%).';return}if(data.type==='error'){failed(data.error);return}if(data.type==='complete'){state.running=false;const previousRates=state.previousBrowserWinRates||{};state.browserMatches=data.matches;state.previousBrowserWinRates=Object.fromEntries(data.matches.map(match=>[match.opponent,browserWinRate(match)]));$('simulation-progress').hidden=true;$('results-empty').hidden=true;$('results-table-wrap').hidden=false;$('matches').innerHTML=data.matches.map(match=>'<tr tabindex="0" data-browser-opponent="'+esc(match.opponent)+'"><td>'+esc(match.opponent)+'</td><td>'+match.wins+'</td><td>'+match.losses+'</td><td>'+match.draws+'</td>'+browserWinRateCell(match,previousRates)+'</tr>').join('');$('status').textContent='Simulation complete.';updateNavigation();setView('results');return}if(data.type==='replay'){const battle=data.battle;renderBrowserLog(battle);setView('logs')}};return simulationWorker}
function browserNarration(event){if(event.includes(' | draw'))return event.split(' | ')[0]+' drew a card.';if(event.includes(' | play:'))return event.split(' | ')[0]+' plays '+name(event.split('play:')[1])+'.';if(event.startsWith('system | battle_end:')){const [,outcome,reason]=event.split(':');return outcome==='draw'?'The battle ended in a draw ('+reason+').':outcome+' wins ('+reason+').'}return state.pool.reduce((text,current)=>text.replaceAll(current.card_id,current.display_name),event)}
$('submit').onclick=()=>{try{if(deckSize()<state.config.minimum_deck_size||deckSize()>state.config.maximum_deck_size){$('status').textContent=deckMessage();return}state.running=true;state.session='browser';state.match=null;state.logNumber=null;state.browserSubmission=currentDeckPayload();$('match-panel').hidden=true;$('results-empty').hidden=false;$('results-table-wrap').hidden=true;$('simulation-progress').hidden=false;$('simulation-progress').value=0;setView('results');updateNavigation();$('status').textContent='Starting browser simulations in a background worker…';worker().postMessage({type:'simulate',opponents:state.publicOpponents,submission:state.browserSubmission,games:+$('games').value,actionLimit:+$('action-limit').value})}catch(error){state.running=false;$('status').textContent=error.message;setView('program')}};
function browserMatch(opponent){const match=state.browserMatches.find(item=>item.opponent===opponent);if(!match)return;state.match=opponent;state.browserMatch=match;state.battlePage=0;$('results-table-wrap').hidden=true;$('match-panel').hidden=false;$('match-title').textContent=state.browserSubmission.owner_name+' vs. '+match.opponent_deck.owner_name;renderBrowserBattlePage();$('status').textContent='';setView('results')}
function renderBrowserBattlePage(){const match=state.browserMatch,start=state.battlePage*10,records=match.battles.slice(start,start+10),pages=Math.ceil(match.battles.length/10),end=Math.min(start+records.length,match.battles.length);$('battles').innerHTML=records.map(b=>'<tr tabindex="0" data-browser-battle="'+b.game_number+'"><td>'+b.game_number+'</td><td>'+esc(b.winner_id===null?'Draw':b.winner_id==='first'?'Win':'Loss')+'</td><td>'+b.first_victory_points+'-'+b.second_victory_points+'</td><td>'+esc(b.end_reason)+'</td></tr>').join('');$('battle-pages').innerHTML='<span class="page-label">Battles '+(start+1)+'–'+end+' of '+match.battles.length+'</span><button data-browser-page-step="-1" '+(state.battlePage===0?'disabled':'')+'>← Previous</button><button data-browser-page-step="1" '+(state.battlePage+1===pages?'disabled':'')+'>Next →</button>'}
document.addEventListener('click',event=>{const opponent=event.target.closest('[data-browser-opponent]');if(opponent){event.stopImmediatePropagation();browserMatch(opponent.dataset.browserOpponent);return}const pageStep=event.target.closest('[data-browser-page-step]');if(pageStep){event.stopImmediatePropagation();state.battlePage+=+pageStep.dataset.browserPageStep;renderBrowserBattlePage();return}const battle=event.target.closest('[data-browser-battle]');if(battle){event.stopImmediatePropagation();const record=state.browserMatch.battles.find(item=>item.game_number===+battle.dataset.browserBattle);if(record){state.logNumber=record.game_number;worker().postMessage({type:'replay',submission:state.browserSubmission,opponent:state.match,seed:record.seed,gameNumber:record.game_number,actionLimit:+$('action-limit').value})}return}},true);

function playerLabel(id){return id==='first'?state.browserSubmission.owner_name:state.browserMatch.opponent_deck.owner_name}
function readableBattleEvent(event){if(event.endsWith(' | turn_start'))return playerLabel(event.split(' | ')[0])+' begins their turn.';if(event.includes(' | draw'))return playerLabel(event.split(' | ')[0])+' drew a card.';if(event.includes(' | play:'))return playerLabel(event.split(' | ')[0])+' played '+name(event.split('play:')[1])+'.';if(event.endsWith(' | end_turn_action'))return playerLabel(event.split(' | ')[0])+' ended their turn.';if(event.startsWith('system | battle_end:')){const [,winner,reason]=event.split(':');const ending={victory_points:'by reaching the victory-point goal',cards_exhausted:'when both decks ran out of cards',action_limit:'when the action limit was reached',action_limit_tie:'when the action limit was reached'}[reason]||'('+reason+')';return winner==='draw'?'The battle ended in a draw '+ending+'.':playerLabel(winner)+' won '+ending+'.'}return ''}
function battleTurns(events){const turns=[];let current;for(const event of events){if(event.endsWith(' | turn_start')){current=[];turns.push(current)}const line=readableBattleEvent(event);if(line){if(!current){current=[];turns.push(current)}current.push(line)}}return turns.filter(turn=>turn.length)}
function renderBrowserLog(battle){state.logTurns=battleTurns(battle.log);state.logTurnIndex=0;state.logMode='full';$('log-title').textContent='Battle '+battle.game_number;renderLogDisplay()}
function renderLogDisplay(){const turns=state.logTurns||[];const viewingTurns=state.logMode==='turns';const visible=viewingTurns?(turns[state.logTurnIndex]||[]):turns.flat();$('log').textContent=visible.join('\n');if(!viewingTurns){$('log-controls').innerHTML='<button data-log-mode="turns">View Turns</button>';return}const first=state.logTurnIndex===0,last=state.logTurnIndex===turns.length-1;$('log-controls').innerHTML='<button data-log-mode="full">Show Full Log</button><span class="log-turn-label">Turn '+(state.logTurnIndex+1)+' of '+turns.length+'</span><button data-log-turn="-1" '+(first?'disabled':'')+'>← Prev Turn</button><button class="next-turn" data-log-turn="1" '+(last?'disabled':'')+'>Next Turn →</button>'}
document.addEventListener('click',event=>{const mode=event.target.closest('[data-log-mode]');if(mode){state.logMode=mode.dataset.logMode;state.logTurnIndex=0;renderLogDisplay();return}const turn=event.target.closest('[data-log-turn]');if(turn){state.logTurnIndex=Math.max(0,Math.min((state.logTurns||[]).length-1,state.logTurnIndex+Number(turn.dataset.logTurn)));renderLogDisplay()}},true);
