const sequence = (...effects) => ({ type: "sequence", effects });
const mechanic = (value) => ({ type: "mechanic", mechanic: value });
const canonical = (effects, text) => ({ effects, canonical_effect: text, draft_effect: text });
export const CARD_SPECS = {
    victory_point_1: {
        card_id: "victory_point_1",
        display_name: "Core",
        card_kind: "pulse",
        effects: mechanic({ type: "gain_flux", amount: 1 }),
        draft_effect: "Gain 1 Flux.",
    },
    air_five_l: {
        card_id: "air_five_l",
        display_name: "Air 5L",
        card_kind: "pulse",
        keyword_line: "Bandwidth 1",
        bandwidth_cost: 1,
        effects: sequence(mechanic({ type: "remove_opponent_sync", amount: 2 }), mechanic({ type: "remove_own_sync", amount: 1 })),
        draft_effect: "Your opponent loses 2 Sync. You lose 1 Sync.",
    },
    overcharge_gambit: {
        card_id: "overcharge_gambit",
        display_name: "Kaioken",
        card_kind: "pulse",
        effects: { type: "conditional", condition: { type: "own_flux_at_most", threshold: 5 }, effect: { type: "gain_flux", amount: 6 } },
        draft_effect: "If you have 5 or fewer Flux, gain 6 Flux.",
    },
    sparkleback_totem: {
        card_id: "sparkleback_totem",
        display_name: "One For All",
        card_kind: "daemon",
        effects: { type: "triggered", trigger: { type: "first_flux_gain_each_turn" }, effect: { type: "gain_flux", amount: 1 } },
        draft_effect: "The first time each turn you gain Flux, gain 1 additional Flux.",
    },
    throttle: {
        card_id: "throttle",
        display_name: "Throttle",
        card_kind: "daemon",
        effects: mechanic({ type: "prevent_next_opponent_flux_gain" }),
        draft_effect: "The next time your opponent would gain Flux, prevent that gain. Then, delete Throttle.",
    },
    download_scan: {
        card_id: "download_scan",
        display_name: "Download",
        card_kind: "pulse",
        effects: mechanic({ type: "scan_deck", count: 5, card_ids: ["victory_point_1"] }),
        draft_effect: "Look at the top 5 cards of your deck and add any Core cards to your hand. Then, put the remaining cards on the bottom in the same order.",
    },
    time_walk: {
        card_id: "time_walk",
        display_name: "Time Walk",
        card_kind: "pulse",
        flux_cost: 10,
        effects: mechanic({ type: "queue_extra_turn" }),
        draft_effect: "Pay 10 Flux: At the end of your turn, take an extra turn.",
    },
    seal: {
        card_id: "seal",
        display_name: "Seal",
        card_kind: "glitch",
        sync_cost: 2,
        reaction_triggers: ["opponent_would_gain_flux"],
        effects: mechanic({ type: "prevent_triggering_event" }),
        draft_effect: "When your opponent would gain Flux, you may pay 2 Sync and play this card. If you do, prevent that gain.",
    },
    clone_jutsu: {
        card_id: "clone_jutsu",
        display_name: "Clone Jutsu",
        card_kind: "pulse",
        jutsu: true,
        signs: ["ram", "ram"],
        effects: mechanic({ type: "create_agents", amount: 2, display_name: "Clone", integrity: 1 }),
        draft_effect: "Create 2 Clone Agents, each with Integrity 1.",
    },
    ninjutsu: {
        card_id: "ninjutsu",
        display_name: "Ninjutsu",
        card_kind: "immutable",
        immutable: true,
        activation: "passive",
        supports_jutsu_preparation: true,
        effects: { type: "jutsu_preparation", maxPrepared: 1 },
        draft_effect: "You may play a Jutsu as a Prepared Jutsu by paying its non-Sign costs and putting it beneath this card instead of resolving it. You can't have more than one Prepared Jutsu beneath this card at a time.",
        traceability: {
            ruleIds: ["800.7a"],
            claimIds: ["800.7a.coverage"],
            ownerIds: ["Battle.play"],
            evidenceIds: ["phase2.600.1b.prepared-jutsu"],
        },
    },
    victory_point_2: {
        card_id: "victory_point_2",
        display_name: "Twin Core",
        card_kind: "pulse",
        keyword_line: "Bandwidth 1",
        bandwidth_cost: 1,
        ...canonical(mechanic({ type: "gain_flux", amount: 2 }), "Gain 2 Flux."),
    },
    threefold_siphon: {
        card_id: "threefold_siphon",
        display_name: "Spirit Gun",
        card_kind: "pulse",
        ...canonical(mechanic({ type: "remove_opponent_victory_points", amount: 3 }), "Remove 3 Flux from your opponent."),
    },
    cursed_seal: {
        card_id: "cursed_seal",
        display_name: "Cursed Seal",
        card_kind: "pulse",
        ...canonical(sequence(mechanic({ type: "set_own_sync_and_draw_half_deck", sync: 1 }), mechanic({ type: "end_own_turn" })), "Reduce your Sync to 1, draw half your remaining deck rounded down. End your turn."),
    },
    five_l: {
        card_id: "five_l",
        display_name: "5L",
        card_kind: "pulse",
        ...canonical(mechanic({ type: "remove_opponent_sync", amount: 1 }), "Your opponent loses 1 Sync."),
    },
    one_more_roll: {
        card_id: "one_more_roll",
        display_name: "One More Roll",
        card_kind: "pulse",
        ...canonical(mechanic({ type: "draw_two_if_hand_empty_otherwise_discard_random" }), "If your hand is empty, draw two cards. Otherwise, discard a card at random."),
    },
    charge_ki: {
        card_id: "charge_ki",
        display_name: "Charge Ki",
        card_kind: "immutable",
        immutable: true,
        activation_limit: "repeatable",
        requires_no_prior_play: true,
        ...canonical(sequence(mechanic({ type: "gain_ki", amount: 1 }), mechanic({ type: "end_own_turn" })), "Activate this card only if you haven't played a card this turn. Gain 1 Ki. End your turn."),
    },
    scrappy_kamehameha: {
        card_id: "scrappy_kamehameha",
        display_name: "Scrappy Kamehameha",
        card_kind: "pulse",
        minimum_ki: 1,
        bandwidth_cost: 1,
        ...canonical(mechanic({ type: "deal_damage", amount: 3 }), "Play this card only if you have 1 or more Ki. When it enters play, it deals 3 damage."),
    },
    farmer_with_shotgun: {
        card_id: "farmer_with_shotgun",
        display_name: "Farmer With Shotgun",
        card_kind: "agent",
        integrity: 1,
        ...canonical({ type: "sequence", effects: [] }, ""),
        traceability: {
            ruleIds: ["900.13a"],
            claimIds: ["900.13a.agent-printed-integrity"],
            ownerIds: ["Battle.player", "Battle.applyScenarioSetup"],
            evidenceIds: ["700.15b.agent-entry"],
        },
    },
    raditz_invader: {
        card_id: "raditz_invader",
        display_name: "Raditz, Invader",
        card_kind: "agent",
        keyword_line: "Bandwidth 2 • Integrity 4 • Breach 1 • Signature: Double Sunday",
        bandwidth_cost: 2,
        integrity: 4,
        breach: 1,
        signature_card_id: "double_sunday",
        ...canonical({ type: "sequence", effects: [] }, ""),
        traceability: {
            ruleIds: ["700.1f", "900.16b"],
            claimIds: ["700.1f.coverage", "900.16b.coverage"],
            ownerIds: ["Battle.resolveEndPhaseTriggers"],
            evidenceIds: ["phase3.setup-turns", "phase3.procedures"],
        },
    },
    double_sunday: {
        card_id: "double_sunday",
        display_name: "Double Sunday",
        card_kind: "pulse",
        keyword_line: "Ki 1",
        signature: true,
        minimum_ki: 1,
        ...canonical(sequence(mechanic({ type: "deal_damage", amount: 1 }), mechanic({ type: "deal_damage", amount: 1 })), "Deal 1 damage. Deal 1 damage."),
    },
    fire_release_great_fireball: {
        card_id: "fire_release_great_fireball",
        display_name: "Fire Release: Great Fireball Technique",
        card_kind: "pulse",
        jutsu: true,
        signs: ["tiger", "ox", "tiger"],
        bandwidth_cost: 2,
        ...canonical(mechanic({ type: "deal_damage", amount: 6 }), "Deal 6 damage."),
    },
    naruto_knuckleheaded_ninja: {
        card_id: "naruto_knuckleheaded_ninja",
        display_name: "Naruto, Knuckleheaded Ninja",
        card_kind: "agent",
        keyword_line: "Bandwidth 1 • Integrity 2 • Breach 1 • Signature: Vandalize the Hokage Monument",
        bandwidth_cost: 1,
        integrity: 2,
        breach: 1,
        max_plays_per_turn: 1,
        signature_card_id: "vandalize_hokage_monument",
        ...canonical({ type: "sequence", effects: [] }, ""),
        traceability: {
            ruleIds: ["900.13a"],
            claimIds: ["900.13a.agent-printed-integrity"],
            ownerIds: ["Battle.player", "Battle.applyScenarioSetup"],
            evidenceIds: ["700.15b.agent-entry"],
        },
    },
    vandalize_hokage_monument: {
        card_id: "vandalize_hokage_monument",
        display_name: "Vandalize the Hokage Monument",
        card_kind: "mission",
        keyword_line: "Bandwidth 1 • Goal 1",
        bandwidth_cost: 1,
        signature: true,
        mission_goal: 1,
        mission_requirement: { type: "control_named_agent", card_id: "naruto_knuckleheaded_ninja" },
        mission_complete_mechanics: [{ type: "gain_flux", amount: 2 }],
        mission_grants_signature_card_id: "shadow_clone_jutsu",
        mission_signature_agent_card_id: "naruto_knuckleheaded_ninja",
        effects: mechanic({ type: "gain_flux", amount: 1 }),
        canonical_effect: "When this enters play, gain 1 Flux. This Mission completes only while you control Naruto, Knuckleheaded Ninja. Complete — For the rest of the battle, Naruto Agents you own gain an additional Signature: Shadow Clone Jutsu; then gain 2 Flux.",
        draft_effect: "When this enters play, gain 1 Flux. This Mission completes only while you control Naruto, Knuckleheaded Ninja. Complete — For the rest of the battle, Naruto Agents you own gain an additional Signature: Shadow Clone Jutsu; then gain 2 Flux.",
    },
    shadow_clone_jutsu: {
        card_id: "shadow_clone_jutsu",
        display_name: "Shadow Clone Jutsu",
        card_kind: "pulse",
        keyword_line: "Bandwidth 1 • Signs: Ram, Ram",
        bandwidth_cost: 1,
        signature: true,
        jutsu: true,
        signs: ["ram", "ram"],
        effects: mechanic({ type: "create_copies_of_highest_breach_agent", amount: 2, eligible_card_ids: ["naruto_knuckleheaded_ninja"] }),
        canonical_effect: "Choose the Naruto Agent you control with the highest Breach, breaking ties by oldest. Create 2 printed copies of it.",
        draft_effect: "Choose the Naruto Agent you control with the highest Breach, breaking ties by oldest. Create 2 printed copies of it.",
    },
    transformation_jutsu: {
        card_id: "transformation_jutsu",
        display_name: "Transformation Jutsu",
        card_kind: "daemon",
        keyword_line: "Bandwidth 1 • Module • Jutsu • Signs: Ram, Snake",
        bandwidth_cost: 1,
        jutsu: true,
        signs: ["ram", "snake"],
        module: true,
        programmed_target: { controller: "self", card_kind: "agent", zone: "battlefield" },
        effects: mechanic({ type: "module_attach_highest_breach_protect" }),
        canonical_effect: "When this enters play, attach it to an Agent you specify. The first time that Agent would be chosen to take damage, if another Agent can take that damage, ignore the attached Agent, then delete this Module.",
        draft_effect: "When this enters play, attach it to an Agent you specify. The first time that Agent would be chosen to take damage, if another Agent can take that damage, ignore the attached Agent, then delete this Module.",
    },
    substitution_jutsu: {
        card_id: "substitution_jutsu",
        display_name: "Substitution Jutsu",
        card_kind: "glitch",
        keyword_line: "Jutsu • Signs: —",
        sync_cost: 2,
        jutsu: true,
        signs: [],
        reaction_triggers: ["own_agent_would_be_deleted"],
        programmed_target: { controller: "self", card_kind: "agent", zone: "battlefield" },
        effects: sequence(mechanic({ type: "prevent_triggering_agent_deletion", minimum_integrity: 1 }), mechanic({ type: "deal_damage", amount: 1 })),
        canonical_effect: "You lose 2 Sync. When an Agent you control would be deleted, you may resolve this card. If you do, prevent that deletion, set that Agent's Integrity to 1 if it is lower, then deal 1 damage to your opponent.",
        draft_effect: "You lose 2 Sync. When an Agent you control would be deleted, you may resolve this card. If you do, prevent that deletion, set that Agent's Integrity to 1 if it is lower, then deal 1 damage to your opponent.",
    },
    kakashi_distracted_mentor: {
        card_id: "kakashi_distracted_mentor",
        display_name: "Kakashi, Distracted Mentor",
        card_kind: "agent",
        keyword_line: "Bandwidth 2 • Integrity 4 • Breach 1 • Signature: Demonic Illusion: Hell Viewing Technique",
        bandwidth_cost: 2,
        integrity: 4,
        breach: 1,
        signature_card_id: "demonic_illusion_hell_viewing_technique",
        ...canonical({ type: "sequence", effects: [] }, ""),
        traceability: {
            ruleIds: ["900.13a"],
            claimIds: ["900.13a.agent-printed-integrity"],
            ownerIds: ["Battle.player", "Battle.applyScenarioSetup"],
            evidenceIds: ["700.15b.agent-entry"],
        },
    },
    demonic_illusion_hell_viewing_technique: {
        card_id: "demonic_illusion_hell_viewing_technique",
        display_name: "Demonic Illusion: Hell Viewing Technique",
        card_kind: "glitch",
        keyword_line: "Glitch Jutsu",
        signature: true,
        jutsu: true,
        signs: [],
        reaction_triggers: ["opponent_would_gain_flux"],
        effects: mechanic({ type: "prevent_all_opponent_flux_gain" }),
        canonical_effect: "Whenever your opponent would gain Flux, prevent that Flux gain.",
        draft_effect: "Whenever your opponent would gain Flux, prevent that Flux gain.",
    },
    dragon_install: {
        card_id: "dragon_install",
        display_name: "Dragon Install",
        card_kind: "daemon",
        ...canonical(sequence(mechanic({ type: "remove_own_sync", amount: 8 }), mechanic({ type: "opponent_sync_loss_bonus", amount: 1 })), "You lose 8 Sync. Whenever a card you control causes your opponent to lose Sync, they lose an additional 1 Sync."),
    },
    dixie_flatline: {
        card_id: "dixie_flatline",
        display_name: "Dixie Flatline",
        card_kind: "daemon",
        ...canonical(mechanic({ type: "restore_sync_when_zero_and_delete_self", sync: 3 }), "When your Sync becomes 0, set your Sync to 3, then delete this card."),
    },
    matt_daemon: {
        card_id: "matt_daemon",
        display_name: "Matt Daemon",
        card_kind: "daemon",
        bandwidth_cost: 2,
        ...canonical(mechanic({ type: "draw_when_another_copy_played" }), "The first time each turn another Matt Daemon enters play under your control, draw a card."),
    },
    rampant_growth: {
        card_id: "rampant_growth",
        display_name: "Rampant Growth",
        card_kind: "pulse",
        keyword_line: "Bandwidth 2",
        bandwidth_cost: 2,
        ...canonical(mechanic({ type: "lose_own_agent_integrity_for_flux", amount: 1 }), "All Agents you control lose 1 Integrity. Gain 1 Flux for each Integrity lost this way."),
    },
    system_backdoor: {
        card_id: "system_backdoor",
        display_name: "System Backdoor",
        card_kind: "pulse",
        keyword_line: "Bandwidth 1",
        bandwidth_cost: 1,
        ...canonical(mechanic({ type: "play_top_card_of_deck", target: "opponent", fallback: "bottom" }), "Play the top card of your opponent's deck if able. If not, put it on the bottom of their deck."),
    },
    red_ribbon_funding: {
        card_id: "red_ribbon_funding",
        display_name: "Red Ribbon Funding",
        card_kind: "pulse",
        keyword_line: "Bandwidth 1",
        bandwidth_cost: 1,
        ...canonical(mechanic({ type: "modify_all_own_agents_breach", amount: 1 }), "Agents you control gain Breach 1."),
    },
    scorched_earth: {
        card_id: "scorched_earth",
        display_name: "Scorched Earth",
        card_kind: "pulse",
        keyword_line: "Bandwidth 3",
        bandwidth_cost: 3,
        ...canonical(mechanic({ type: "destroy_all_agents_and_daemons" }), "Delete every Agent and Daemon on both battlefields."),
    },
    core_values: {
        card_id: "core_values",
        display_name: "Core Values",
        card_kind: "immutable",
        activation: "active",
        activation_limit: "once_per_battle",
        setup_mechanics: [{ type: "lose_at_setup_if_deck_contains", card_ids: ["victory_point_1", "victory_point_2"] }],
        ...canonical(mechanic({ type: "collect_named_cards_from_deck", card_ids: ["victory_point_1", "victory_point_2"], end_turn: true }), "At the start of the battle, if you have any Core or Twin Core cards in your deck, you lose. You can activate this card once per battle to move all Core and Twin Core cards from your deck to your hand, set your Sync to 1, and end your turn."),
    },
    the_points_icon: {
        card_id: "the_points_icon",
        display_name: "The Points Icon",
        card_kind: "pulse",
        keyword_line: "Bandwidth 10 • Flux 15",
        bandwidth_cost: 10,
        flux_cost: 15,
        ...canonical(mechanic({ type: "gain_flux", amount: 20 }), "Gain 20 Flux."),
    },
    keyboard_roll: {
        card_id: "keyboard_roll",
        display_name: "Keyboard Roll",
        card_kind: "pulse",
        ...canonical(sequence(mechanic({ type: "play_top_card_of_deck", target: "self", fallback: "discard" }), mechanic({ type: "remove_own_sync", amount: 1 })), "Play the top card of your deck if able. If not, put it into your discard pile. Lose 1 Sync."),
    },
    kernel_exploit: {
        card_id: "kernel_exploit",
        display_name: "Kernel Exploit",
        card_kind: "pulse",
        keyword_line: "Bandwidth 10",
        bandwidth_cost: 10,
        ...canonical(sequence(mechanic({ type: "remove_opponent_sync", amount: 10 }), mechanic({ type: "gain_flux", amount: 10 })), "Your opponent loses 10 Sync. Gain 10 Flux."),
    },
    junk_food: {
        card_id: "junk_food",
        display_name: "Junk Food",
        card_kind: "pulse",
        ...canonical(sequence(mechanic({ type: "draw_cards", amount: 3 }), mechanic({ type: "end_own_turn" })), "Draw 3 cards, then end your turn."),
    },
    soul_warden: {
        card_id: "soul_warden",
        display_name: "Soul Warden",
        card_kind: "agent",
        integrity: 1,
        ...canonical(mechanic({ type: "first_daemon_play_gain_flux", amount: 1 }), "The first time a Daemon is successfully played each turn, gain 1 Flux."),
    },
    flux_capacitor: {
        card_id: "flux_capacitor",
        display_name: "Flux Capacitor",
        card_kind: "glitch",
        flux_cost: 2,
        reaction_triggers: ["opponent_would_lose_sync"],
        ...canonical(mechanic({ type: "prevent_triggering_sync_loss" }), "When you would lose Sync during your opponent's turn, you may pay 2 Flux and play this card. If you do, prevent that Sync loss."),
    },
    special_beam_cannon: {
        card_id: "special_beam_cannon",
        display_name: "Special Beam Cannon",
        card_kind: "pulse",
        keyword_line: "Ki cost 1",
        ki_cost: 1,
        ...canonical(mechanic({ type: "deal_damage_chain", amount: 4, decrement: 1 }), "Deal 4 damage. If this deletes an Agent, deal damage again, reduced by 1, and repeat until the next damage amount would be 0."),
    },
    core_for_all: {
        card_id: "core_for_all",
        display_name: "Core for All",
        card_kind: "daemon",
        ...canonical(mechanic({ type: "add_core_on_first_flux_gain" }), "The first time each turn you gain Flux, add a Core to your deck and shuffle."),
    },
    blood_shadow: {
        card_id: "blood_shadow",
        display_name: "Blood Shadow, Spawn of the Bleeding Phoenix",
        card_kind: "agent",
        integrity: 1,
        ...canonical(sequence(mechanic({ type: "start_turn_damage_other_agents_gain_integrity", amount: 1 }), mechanic({ type: "reduce_flux_gain", amount: 1 })), "At the start of your turn, all other Agents on both battlefields lose 1 Integrity. This Agent gains 1 Integrity for each Integrity lost this way. Whenever you would gain Flux, gain 1 less Flux instead."),
    },
    spirit_bomb: {
        card_id: "spirit_bomb",
        display_name: "Spirit Bomb",
        card_kind: "pulse",
        keyword_line: "Ki 2",
        minimum_ki: 2,
        ...canonical(mechanic({ type: "deal_damage_by_own_agent_count" }), "Deal 1 damage for each Agent you control."),
    },
    cultivate: {
        card_id: "cultivate",
        display_name: "Cultivate",
        card_kind: "pulse",
        keyword_line: "Bandwidth 2",
        bandwidth_cost: 2,
        ...canonical(mechanic({ type: "gain_integrity_all_agents", amount: 1 }), "All Agents you control gain 1 Integrity."),
    },
    crush_card_virus: {
        card_id: "crush_card_virus",
        display_name: "Crush Card Virus",
        card_kind: "pulse",
        ...canonical(mechanic({ type: "destroy_random_opponent_daemon" }), "If your opponent has a Daemon card in play, destroy a random Daemon card they control."),
    },
    garbage_collection: {
        card_id: "garbage_collection",
        display_name: "Garbage Collection",
        card_kind: "pulse",
        ...canonical(sequence(mechanic({ type: "recover_random_discard", amount: 2 }), mechanic({ type: "wipe_this_card" })), "Shuffle 2 random cards from your Discard into your deck. Then wipe this card."),
    },
    virus_beetle: {
        card_id: "virus_beetle",
        display_name: "Virus Beetle",
        card_kind: "pulse",
        keyword_line: "Bandwidth 1",
        bandwidth_cost: 1,
        ...canonical(mechanic({ type: "discard_random_card", target: "opponent" }), "Your opponent discards a card at random."),
    },
    core_a_core: {
        card_id: "core_a_core",
        display_name: "Core-a-Core",
        card_kind: "pulse",
        adds_card_ids: ["victory_point_1"],
        ...canonical(sequence(mechanic({ type: "gain_flux", amount: 1 }), mechanic({ type: "add_cards_to_deck", card_id: "victory_point_1", amount: 1, shuffle: true })), "Gain 1 Flux. Add a Core card to your deck and shuffle."),
    },
    two_cores_in_a_box: {
        card_id: "two_cores_in_a_box",
        display_name: "Two Cores (in a box)",
        card_kind: "pulse",
        adds_card_ids: ["victory_point_1"],
        ...canonical(mechanic({ type: "add_cards_to_deck", card_id: "victory_point_1", amount: 2, shuffle: true }), "Add 2 Core cards to your deck and shuffle."),
    },
    admin_override: {
        card_id: "admin_override",
        display_name: "Admin Override",
        card_kind: "pulse",
        ...canonical(sequence(mechanic({ type: "gain_own_sync", amount: 1 }), mechanic({ type: "play_top_card_of_opponent_deck" })), "Gain 1 Sync. Your opponent plays the top card of their deck."),
    },
};
/** Compatibility alias for the initial pilot tests and downstream authoring tools. */
export const PILOT_CARD_SPECS = CARD_SPECS;
